// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentDir() {
  return window['go']['main']['App']['GetCurrentDir']();
}

export function GetFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFile'](arg1, arg2, arg3);
}

export function GetLastError() {
  return window['go']['main']['App']['GetLastError']();
}

export function GetLastSpeed() {
  return window['go']['main']['App']['GetLastSpeed']();
}

export function PutFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PutFile'](arg1, arg2, arg3);
}

export function ReadLogFile() {
  return window['go']['main']['App']['ReadLogFile']();
}

export function SelectWorkingDir() {
  return window['go']['main']['App']['SelectWorkingDir']();
}

export function SetRemoteIp(arg1) {
  return window['go']['main']['App']['SetRemoteIp'](arg1);
}
