// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentDir():Promise<string>;

export function GetFile(arg1:string,arg2:string,arg3:number):Promise<number>;

export function GetLastError():Promise<string>;

export function GetLastSpeed():Promise<string>;

export function PutFile(arg1:string,arg2:string,arg3:number):Promise<number>;

export function ReadLogFile():Promise<string>;

export function SelectWorkingDir():Promise<string>;

export function SetRemoteIp(arg1:string):Promise<void>;
